name: Deploy Release
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get version
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Set Workflow variables
        id: set-workflow-vars
        run: |
          echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Send Release message to slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "release_version": "${{ steps.set-workflow-vars.outputs.version }}",
              "test": ${{ steps.set-workflow-vars.outputs.version }},
              "previoustag": "${{ steps.previoustag.outputs.tag }}",
              "test": ${{ steps.previoustag.outputs.tag }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_WEBHOOK_URL }}

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "docs(all): update changelog"
          git-user-name: "test"
          skip-version-file: "true"
          git-push: "false"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.previoustag.outputs.tag }}
          prerelease: false
